### ISSUE TITLE
Difference between Target dashboard and the Lt-dash

### ISSUE THREAD

**Issue by krishnakanthpps** [dmoll1974/lt-dash#28]
Hi Dan, 

What is the difference between the two dashboards that you have built?

I tried targets-io dashboard and was successfull and it was awesome.

**Comment by dmoll1974** [comment]
Hi Krishna,

Thanks for your kind words :-) May I ask how you found the targets-io dashboard?

lt-dash is just an older version of the targets-io dashboard, in fact I'll remove that repo soon.

cheers

Daniel
